language: ruby

sudo: false

compiler:
  - clang
  - gcc

before_install:
 # LibCouchbase
 #  - wget -O/etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list
 #  - "wget http://packages.couchbase.com/ubuntu/couchbase.key && sudo cat couchbase.key | sudo apt-key add -"

addons:
  apt:
    packages:
    - python-software-properties
    - cmake
    - libgtest-dev
    - libssl-dev
    - libev-dev
    - libevent-dev
    - libcouchbase2
    - libcouchbase-dev

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3

