language: ruby

sudo: true

compiler:
  - clang
  - gcc

before_install:
  - apt-get -y install python-software-properties
  - add-apt-repository -y ppa:mnunberg/cmake
  - apt-get update
  - apt-get -y install libgtest-dev libssl-dev libev-dev libevent-dev cmake

 # LibCouchbase
  - wget -O/etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list
  - "wget http://packages.couchbase.com/ubuntu/couchbase.key && sudo cat couchbase.key | sudo apt-key add -"
  - apt-get update
  - apt-get install libcouchbase2 libcouchbase-dev

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3

