language: ruby

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - python-software-properties
    - cmake
    - libcouchbase
    - libcouchbase-dev
    - libgtest-dev
    - libssl-dev
    - libev-dev
    - libevent-dev
    - libcouchbase2
    - libcouchbase-dev

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3

