language: ruby

# sudo: true

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgtest-dev
      - libssl-dev
      - libev-dev
      - libevent-dev
      - cmake

compiler:
  - clang
  - gcc

install:
  - ./.travis/install.sh

#addons:
#  apt:
#    packages:
#    - python-software-properties
#    - cmake
#    - libcouchbase
#    - libcouchbase-dev
#    - libgtest-dev
#    - libssl-dev
#    - libev-dev
#    - libevent-dev
#    - libcouchbase
#    - libcouchbase-dev

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3


